### ISSUE TITLE
computer says no

### ISSUE THREAD

**Issue by AugustinasS** [justaskz/go-sudoku-solver#1]
main.go:5:2: cannot find package "github.com/leakymirror/sudoku/fixtures" in any of:
        /usr/local/go/src/github.com/leakymirror/sudoku/fixtures (from $GOROOT)
        /home/august/go/src/github.com/leakymirror/sudoku/fixtures (from $GOPATH)

**Comment by justaskz** [comment]
I fixed the code. It should work now

**Comment by AugustinasS** [comment]
compiled succesfully
